title: RDX
description: A bold typographic theme inspired by rdx design.
social_link: rdxtwitter
social_username: rdx
github_repo: rdx
github_username: ramandahiya101
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /rdx
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
